on:
  push

name: Test Transition Issue

jobs:
  test-transition-issue:
    name: Transition Issue
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.TUHIN_JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.TUHIN_JIRA_API_TOKEN }}

    - name: Find Issue Key
      run: |
        commit_range=$(git rev-parse --abbrev-ref HEAD)...HEAD
        commit_messages=$(git log --format=%B $commit_range)
        issue_key=$(echo "$commit_messages" | grep -oE '[A-Z]+-[0-9]+')
        echo "::set-output name=issue::$issue_key"
      with:
        from: commits

    - name: Transition issue
      uses: atlassian/gajira-transition@master
      with:
        issue: ${{ steps.create.outputs.issue }}
        transition: "In Progress"